services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hn\Agent\:
    resource: '../Classes/*'

  Hn\Agent\Domain\AgentTaskRepository:
    public: true

  Hn\Agent\Service\AgentService:
    public: true

  Hn\Agent\Service\DocumentImageExtractorService:
    public: true
